//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by main. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubThing) DeepCopyInto(out *SubThing) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubThing.
func (in *SubThing) DeepCopy() *SubThing {
	if in == nil {
		return nil
	}
	out := new(SubThing)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SuperModule) DeepCopyInto(out *SuperModule) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SuperModule.
func (in *SuperModule) DeepCopy() *SuperModule {
	if in == nil {
		return nil
	}
	out := new(SuperModule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SuperModule) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SuperModuleList) DeepCopyInto(out *SuperModuleList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SuperModule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SuperModuleList.
func (in *SuperModuleList) DeepCopy() *SuperModuleList {
	if in == nil {
		return nil
	}
	out := new(SuperModuleList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SuperModuleList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SuperModuleSpec) DeepCopyInto(out *SuperModuleSpec) {
	*out = *in
	out.SubThing = in.SubThing
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SuperModuleSpec.
func (in *SuperModuleSpec) DeepCopy() *SuperModuleSpec {
	if in == nil {
		return nil
	}
	out := new(SuperModuleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SuperModuleStatus) DeepCopyInto(out *SuperModuleStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SuperModuleStatus.
func (in *SuperModuleStatus) DeepCopy() *SuperModuleStatus {
	if in == nil {
		return nil
	}
	out := new(SuperModuleStatus)
	in.DeepCopyInto(out)
	return out
}
